### PR TITLE
updated pkgs

### PR DESCRIPTION
**Pull request by oberon2007**
* Created height-patch (what exactly does it fix btw?)
* some adjustments and corrections to the PKGBUILDs
* dmenurc: reverted to urxvt and i3 customization

### CODE REVIEW

**Comment by Chrysostomus** [comment]
The height patch allows passin -h N argument to dmenu, where N is desired heoght of single dmenu line. Awesome respin uses this to make dmenu exactly the same size as top panel.

**Comment by oberon2007** [comment]
Ok. cool! :) Packages are pushed to unstable plus testing.

**Comment by oberon2007** [comment]
Could we not define the -h N argument also in .dmenurc and call it from dmenu_recency in case the variable is present?

**Comment by Chrysostomus** [comment]
We could, but I think it is better to leave it to be specified on runtime. For example: if running dmenu_recent normally, I prefer to set height to $PANEL_HEIGHT, but if I run it with -l 10 option, $PANEL_HEIGHT is unnecessarily thick for single line.

**Comment by oberon2007** [comment]
ok. that makes sense! :)

**Pull request merged**
